"""FastAPI entrypoint for the Hyperswitch coverage dashboard."""

import os
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from routes import pages, api

app = FastAPI(
    title="Hyperswitch Coverage Dashboard",
    description="Feature inventory + cypress coverage tracker",
    version="1.0.0",
)

app.include_router(pages.router)
app.include_router(api.router, prefix="/api")

app.mount("/static", StaticFiles(directory="static"), name="static")

# Expose the existing /repo so dashboard.html (generated by build_dashboard.py)
# can be served as the trends page.
REPO_ROOT = os.environ.get("REPO_ROOT", "/repo")
if os.path.isdir(REPO_ROOT):
    app.mount("/repo", StaticFiles(directory=REPO_ROOT), name="repo")
